#!/bin/bash

# add color to commands
alias \
	grep="grep --color=auto" \
	dir='dir --color=auto'

# shortcuts
alias \
	untar="tar -xvf" \
	vim="nvim" \
	v="nvim" \
	cp="cp -iv" \
	..="cd .." \
	mv="mv -iv" \
	dot='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME' \
	reload-profile="source ~/.config/zsh/.zshrc" \
	weather="curl wttr.in"

# Git things, use `,` as vimprefix so....
alias ,=git	\
	,gg=lazygit \
	,s="git status"	\
	,l="git log" \
	,f="git fetch --all" \
	,c="git checkout" \
	,stash="git stash" \
	,glog="git glog" \
	,show="git sshow" \
	,dft="git dft"

weather-short() {
	curl -m 1 'wttr.in?format=3' 2>/dev/null
	sleep 900
}

# search for all scripts and dotfiles, then open them with editor of choice
sc() {
	find ~/ ~/.config ~/.local/bin ~/.local/share/rais -type f \
		| fzf  --preview 'bat --color=always --line-range :50 {}' | xargs -r "$EDITOR" ;
	}

# fd - cd into any hidden directory of the current folder
fcd() {
	local dir
	dir=$(find "${1:-.}" -type d 2> /dev/null | fzf +m) && cd "$dir"
}

# cdf - cd into the directory of the selected file
cdf() {
	local file
	local dir
	file=$(find "${1:-.}" -type f | fzf +m -q "$1") && dir=$(dirname "$file") && cd "$dir"
}
if type z &>/dev/null; then
	alias cd="z"
fi
if type exa &>/dev/null; then
	# enable color support of ls and also add handy aliases
	alias ls="exa --color=always" \
		ll='exa -lh --git --group --modified --icons'
fi
if type fzf &>/dev/null; then
	alias ,ff='v $(fzf)'
fi
if type wishlist &>/dev/null; then
	alias sshlist=wishlist
fi

print_colours() {
	for i in {0..255}; do
		printf "\x1b[38;5;${i}mcolour${i}\x1b[0m\n"
	done
}

if type fdfind &>/dev/null; then 
	alias fd=fdfind
fi
if type tmux &>/dev/null; then 
	alias tn=tmux new -s "$(pwd | sed 's/.*\///g')"
fi
