#!/usr/bin/env sh
#              _           _
#             | |         (_)
#  _   _  __ _| |__   __ _ _ _ __ ___
# | | | |/ _` | '_ \ / _` | | '__/ __|
# | |_| | (_| | |_) | (_| | | | | (__
#  \__, |\__,_|_.__/ \__,_|_|_|  \___|
#   __/ |
#  |___/

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  06
yabai -m config bottom_padding               06
yabai -m config left_padding                 06
yabai -m config right_padding                06
yabai -m config window_gap                   06

# Spaces
yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5

# float preferences
# yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Synergy$" manage=off
# Title based rules
yabai -m rule --add title="Preferences" manage=off topmost=on
yabai -m rule --add title="^Open Resource$" manage=off
yabai -m rule --add title="^Import$" manage=off
yabai -m rule --add app="^Eclipse$" manage=off
yabai -m rule --add app="^GIMP$" manage=off

# global settings
yabai -m config status_bar                   on
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# yabai -m config external_bar all:0:30
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
# yabai -m signal --add event=space_changed action="sketchybar --trigger windows_on_spaces"

echo "yabai configuration loaded.."
