return {
	bashls = require("servers.bashls"),
	cssls = require("servers.cssls"),
	dockerls = require("servers.dockerls"),
	html = require("servers.html"),
	jsonls = require("servers.jsonls"),
	ruff = require("servers.ruff"),
	stylelint_lsp = { autostart = false },
	lua_ls = require("servers.lua_ls"),
	tailwindcss = require("servers.tailwindcss"),
	terraformls = require("servers.terraformls"),
	tflint = require("servers.tflint"),
	vtsls = require("servers.vtsls"),
	yamlls = require("servers.yamlls"),
}
	-- eslint = require("servers.eslint"),
	-- kulala_ls = require("servers.kulala_ls"),
	-- hausify = require("servers.hausify"),
	-- basedpyright = require("servers.basedpyright"),
	-- tsgo = require("servers.tsgo"),
	-- ts_ls = require("servers.ts_ls"),
	-- ty = require("servers.ty"),
